### ISSUE TITLE
[Release Request] Missing 10.9.0-10.9.2 releases missing

### ISSUE THREAD

**Issue by REJack** [binhex/arch-jellyfin#8]
Hey binhex, 

could you please publish a new release for jellyfin? I cant use the server with the desktop client anymore.

**Comment by vdubedout** [comment]
Yep, client says "This server needs to be updated. To download the latest version please visit [...]"
Sent you a bunch of beer through Paypal to ease the process 👍 

Thanks <3

**Comment by binhex** [comment]
Hi guys i am aware of this, the hold up on the release is due to the fact im awaiting the upstream package maintainer to update the jellyfin package, link:- https://archlinux.org/packages/extra/x86_64/jellyfin-server/

once the upstream package maintainer has updated, my scripts will auto trigger a new docker image build.
